// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcrHqGahAcKvX_8MnncU4TKPN_YVuCtqM',
    appId: '1:701855470507:web:47deb5153cb63430c378ee',
    messagingSenderId: '701855470507',
    projectId: 'employeeapp-2a21c',
    authDomain: 'employeeapp-2a21c.firebaseapp.com',
    storageBucket: 'employeeapp-2a21c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAreD_XDPQTrBCRR7e2LzNOy01fqNKTBS0',
    appId: '1:701855470507:android:694551645f95a268c378ee',
    messagingSenderId: '701855470507',
    projectId: 'employeeapp-2a21c',
    storageBucket: 'employeeapp-2a21c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_iX_ih0Kz8-0kFOorOSNGmsFY5XHnFl4',
    appId: '1:701855470507:ios:2d6b9c5bd73aff21c378ee',
    messagingSenderId: '701855470507',
    projectId: 'employeeapp-2a21c',
    storageBucket: 'employeeapp-2a21c.firebasestorage.app',
    iosBundleId: 'com.example.employeeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_iX_ih0Kz8-0kFOorOSNGmsFY5XHnFl4',
    appId: '1:701855470507:ios:2d6b9c5bd73aff21c378ee',
    messagingSenderId: '701855470507',
    projectId: 'employeeapp-2a21c',
    storageBucket: 'employeeapp-2a21c.firebasestorage.app',
    iosBundleId: 'com.example.employeeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcrHqGahAcKvX_8MnncU4TKPN_YVuCtqM',
    appId: '1:701855470507:web:aaac05b900078fcec378ee',
    messagingSenderId: '701855470507',
    projectId: 'employeeapp-2a21c',
    authDomain: 'employeeapp-2a21c.firebaseapp.com',
    storageBucket: 'employeeapp-2a21c.firebasestorage.app',
  );
}
